### ISSUE TITLE
confused by the contact matrices

### ISSUE THREAD

**Issue by JasonJYang** [kieshaprem/covid19-agestructureSEIR-wuhan-social-distancing#2]
Thanks for your great work!
Would you mind telling me where to download the original contact matrices? I have read the paper from Prem, Cook, and Jit (2017), and I found a supporting dataset which contains the location-specific contact matrices of 152 countries. However, I found the original contact matrices of China is different from yours. Could you tell me whether you did some pre-processing on them? Thanks!

**Comment by kieshaprem** [comment]
Many thanks for reaching out. It could be an error when we were exporting to .xlsx, but I have added the .Rdata files which we use for modelling work. I hope it helps. 

Link to the contacts.Rdata file: https://github.com/kieshaprem/covid19-agestructureSEIR-wuhan-social-distancing/blob/master/data/contacts.Rdata

**Comment by JasonJYang** [comment]
> Many thanks for reaching out. It could be an error when we were exporting to .xlsx, but I have added the .Rdata files which we use for modelling work. I hope it helps.
> 
> Link to the contacts.Rdata file: https://github.com/kieshaprem/covid19-agestructureSEIR-wuhan-social-distancing/blob/master/data/contacts.Rdata

Thank you very much!!! It is really useful. Thanks again!
